apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/part-of: coolstore-inventory
  name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
  namespace: agroom-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:62111cd5bcf106458c8b6ee48395ade7e1a6c74429c4445ea85db3276961a53f
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
