apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/part-of: coolstore-inventory
  name: labsinventory-quarkus-endzvih
  namespace: agroom-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    weight: 100
status: {}
