apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
    app.kubernetes.io/part-of: coolstore-inventory
  name: labsinventory-quarkus-end-to-end-developer-workshop-crjr
  namespace: agroom-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: labsinventory-quarkus-end-to-end-developer-workshop-crjr
status:
  loadBalancer: {}
